plugins {
    `java-library`
    `java-test-fixtures`
}

evaluationDependsOn(":ocgcore-native")
val native = project(":ocgcore-native")

sourceSets {
    main {
        java.srcDir("src/generated/java")
        resources.srcDir("src/generated/resources")
    }
}

dependencies {
    // Provided by Minecraft at runtime inside the mod; declared normally for the standalone engine/tests.
    api(libs.gson)
    implementation(libs.slf4j.api)

    testFixturesApi(platform(libs.junit.bom))
    testFixturesApi(libs.junit.jupiter)
    testFixturesApi(libs.assertj)
    testFixturesImplementation(libs.sqlite.jdbc)

    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj)
    testRuntimeOnly(libs.junit.platform.launcher)
    testRuntimeOnly(libs.slf4j.simple)
}

val upstreamDir = rootProject.layout.buildDirectory.dir("upstream")

tasks.test {
    dependsOn(":ocgcore-native:cmakeBuildHost", ":syncUpstreamCardScripts", ":syncUpstreamBabelCdb")
    @Suppress("UNCHECKED_CAST")
    systemProperty("ygo.ocgcore.path", (native.extra["hostLibrary"] as Provider<String>).get())
    @Suppress("UNCHECKED_CAST")
    systemProperty("ygo.ocgcore.layoutProbe", (native.extra["layoutProbe"] as Provider<String>).get())
    systemProperty("ygo.upstream.dir", upstreamDir.get().asFile.absolutePath)
    systemProperty("org.slf4j.simpleLogger.defaultLogLevel", "info")
    maxHeapSize = "1g"
}

// ---------------------------------------------------------------------------------------------
// OcgConstants.java is generated from ocgapi_constants.h (values evaluated by the C++ compiler via
// ocg_constants_dump) and committed, so the engine compiles without a native toolchain.
// ---------------------------------------------------------------------------------------------
val constantsFile = layout.projectDirectory.file(
    "src/generated/java/io/github/zancrow321/minecraftygo/engine/constants/OcgConstants.java"
)

fun renderConstants(dumpOutput: String): String {
    val longPrefixes = listOf("DUEL_", "RACE_", "OPCODE_")
    val body = StringBuilder()
    var lastGroup = ""
    for (line in dumpOutput.lines().filter(String::isNotBlank)) {
        val (name, raw) = line.trim().split('=', limit = 2)
        val value = raw.toULong()
        val group = name.substringBefore('_')
        if (group != lastGroup && body.isNotEmpty()) body.append('\n')
        lastGroup = group
        val isLong = (longPrefixes.any(name::startsWith) && !name.endsWith("_FORB")) || value > 0xFFFFFFFFu
        if (isLong) {
            body.append("    public static final long $name = 0x${value.toString(16).uppercase()}L;\n")
        } else {
            body.append("    public static final int $name = 0x${value.toString(16).uppercase()};\n")
        }
    }
    return """
        |// GENERATED by :engine:generateOcgConstants from ygopro-core/ocgapi_constants.h - do not edit.
        |// SPDX-License-Identifier: AGPL-3.0-or-later
        |package io.github.zancrow321.minecraftygo.engine.constants;
        |
        |/** Constants of the ocgcore C API (ocgapi_types.h / ocgapi_constants.h). */
        |@SuppressWarnings("unused")
        |public final class OcgConstants {
        |    private OcgConstants() {}
        |
        |""".trimMargin() + body + "}\n"
}

fun dumpConstants(): String {
    @Suppress("UNCHECKED_CAST")
    val exe = (native.extra["constantsDump"] as Provider<String>).get()
    val process = ProcessBuilder(exe).redirectErrorStream(true).start()
    val output = process.inputStream.bufferedReader().readText()
    check(process.waitFor() == 0) { "ocg_constants_dump failed:\n$output" }
    return output
}

tasks.register("generateOcgConstants") {
    group = "native"
    description = "Regenerates OcgConstants.java from the ocgcore headers"
    dependsOn(":ocgcore-native:cmakeBuildHost")
    doLast {
        val target = constantsFile.asFile
        target.parentFile.mkdirs()
        target.writeText(renderConstants(dumpConstants()))
    }
}

val checkOcgConstants = tasks.register("checkOcgConstants") {
    group = "verification"
    description = "Fails if OcgConstants.java is out of date with the ocgcore headers"
    dependsOn(":ocgcore-native:cmakeBuildHost")
    doLast {
        check(constantsFile.asFile.readText() == renderConstants(dumpConstants())) {
            "OcgConstants.java is stale - run ./gradlew :engine:generateOcgConstants"
        }
    }
}
tasks.check { dependsOn(checkOcgConstants) }
