package io.github.zancrow321.minecraftygo.engine.ffi;

/**
 * One native duel instance. Not thread-safe: a duel must only be used by one thread at a time. All returned buffers
 * are copies owned by the caller.
 */
public interface NativeDuel extends AutoCloseable {
	void newCard(NewCard card);

	/** Loads a script into the duel's Lua state; returns false if Lua reported an error. */
	boolean loadScript(String name, byte[] source);

	void start();

	DuelStatus process();

	/** The messages generated by the last {@link #process()} call. */
	byte[] getMessage();

	void setResponse(byte[] response);

	int queryCount(int team, int location);

	byte[] query(QueryRequest request);

	byte[] queryLocation(QueryRequest request);

	byte[] queryField();

	boolean isClosed();

	/** Destroys the native duel; further calls fail. */
	@Override
	void close();
}
