package io.github.zancrow321.minecraftygo.tools.assets;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.github.zancrow321.minecraftygo.tools.bbmodel.BbModel;
import io.github.zancrow321.minecraftygo.tools.bbmodel.GeoConverter;
import io.github.zancrow321.minecraftygo.tools.util.Json;

import javax.imageio.ImageIO;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Hand-made assets (Duel Disk, Duel Arena, Millennium Items, ...) against {@code assets-src/asset-contract.json}:
 * <ul>
 *   <li>{@code assets-src/blockbench/<id>.bbmodel} present: validated (bones, animations, texture size, cube budget,
 *       no reference images) and converted with the same converter as the monsters</li>
 *   <li>missing: a placeholder with every required bone is generated, so the mod never waits for art</li>
 *   <li>the Duel Arena's {@code anchor_*} bones become {@code data/minecraftygo/arena_layout/*.json}</li>
 * </ul>
 * Usage: {@code ProcessAssets <repoRoot> [--check]}; with {@code --check} nothing is written and contract violations
 * fail.
 */
public final class ProcessAssets {
	private static final String NAMESPACE = "minecraftygo";

	public static void main(String[] args) throws IOException {
		Path root = Path.of(args[0]);
		boolean check = args.length > 1 && args[1].equals("--check");
		JsonObject contract = Json.read(root.resolve("assets-src/asset-contract.json")).getAsJsonObject();
		Path sources = root.resolve("assets-src/blockbench");
		Path generated = root.resolve("neoforge/src/generated/resources");
		Path assets = generated.resolve("assets").resolve(NAMESPACE);

		List<String> errors = new ArrayList<>();
		Map<String, String> status = new TreeMap<>();
		JsonObject arenaAnchors = null;
		for (JsonElement element : contract.getAsJsonArray("assets")) {
			JsonObject asset = element.getAsJsonObject();
			String id = asset.get("id").getAsString();
			String kind = asset.get("kind").getAsString();
			Path bbmodelFile = sources.resolve(id + ".bbmodel");
			Path animationFile = sources.resolve(id + ".animation.json");
			JsonObject geometry;
			JsonObject animations;
			byte[] texture;
			if (Files.isRegularFile(bbmodelFile)) {
				List<String> problems = validate(asset, bbmodelFile, animationFile);
				problems.forEach(p -> errors.add(id + ": " + p));
				if (!problems.isEmpty()) {
					status.put(id, "INVALID (" + problems.size() + " problems)");
					continue;
				}
				BbModel model = BbModel.read(bbmodelFile);
				GeoConverter.Result result = GeoConverter.convert(model, "geometry." + NAMESPACE + "." + id);
				geometry = result.geometry();
				animations = Json.read(animationFile).getAsJsonObject();
				texture = texture(sources, id, model);
				if (id.equals("duel_arena")) {
					arenaAnchors = anchorsFromModel(model);
				}
				status.put(id, "source (" + result.cubeCount() + " cubes)");
			} else {
				geometry = placeholderGeometry(asset);
				animations = placeholderAnimations(asset);
				texture = placeholderTexture(asset);
				status.put(id, asset.has("optional") && asset.get("optional").getAsBoolean() ? "placeholder (optional)" : "placeholder");
			}
			if (!check) {
				Json.write(assets.resolve("geckolib/models/" + kind + "/" + id + ".geo.json"), Json.COMPACT.toJson(geometry) + "\n");
				Json.write(assets.resolve("geckolib/animations/" + kind + "/" + id + ".animation.json"), Json.PRETTY.toJson(animations) + "\n");
				Path textureFile = assets.resolve("textures/" + kind + "/" + id + ".png");
				Files.createDirectories(textureFile.getParent());
				Files.write(textureFile, texture);
			}
		}
		if (!check) {
			JsonObject anchors = arenaAnchors != null ? arenaAnchors : ArenaLayouts.defaultAnchors();
			Path layouts = generated.resolve("data").resolve(NAMESPACE).resolve("arena_layout");
			Json.write(layouts.resolve("standard_1v1.json"), Json.PRETTY.toJson(ArenaLayouts.layout(anchors, 1)) + "\n");
			Json.write(layouts.resolve("standard_2v2.json"), Json.PRETTY.toJson(ArenaLayouts.layout(anchors, 2)) + "\n");
			StringBuilder md = new StringBuilder("# Asset status\n\nGenerated by `./gradlew :tools:processAssets` from "
					+ "`assets-src/asset-contract.json`. Placeholders are replaced as soon as `assets-src/blockbench/<id>.bbmodel` "
					+ "(+ `<id>.animation.json`) exist - see `docs/assets.md`.\n\n| Asset | Status |\n|---|---|\n");
			status.forEach((id, s) -> md.append("| ").append(id).append(" | ").append(s).append(" |\n"));
			Json.write(root.resolve("docs/AssetStatus.md"), md.toString());
		}
		status.forEach((id, s) -> System.out.println(id + ": " + s));
		if (!errors.isEmpty()) {
			throw new IllegalStateException("Asset contract violations:\n  " + String.join("\n  ", errors));
		}
	}

	// ---- validation ----------------------------------------------------------------------------------------

	static List<String> validate(JsonObject asset, Path bbmodelFile, Path animationFile) throws IOException {
		List<String> problems = new ArrayList<>();
		String raw = Files.readString(bbmodelFile);
		JsonObject rawJson = com.google.gson.JsonParser.parseString(raw).getAsJsonObject();
		if (rawJson.has("reference_images") && !rawJson.getAsJsonArray("reference_images").isEmpty()) {
			problems.add("contains reference images - remove them before committing");
		}
		if (raw.contains(":\\\\") || raw.contains("\"path\":\"/")) {
			problems.add("contains absolute file paths");
		}
		BbModel model = BbModel.read(bbmodelFile);
		Set<String> groups = new TreeSet<>();
		collectGroups(model.roots, groups);
		for (String bone : asset.getAsJsonObject("bones").keySet()) {
			if (!groups.contains(bone)) {
				problems.add("missing bone '" + bone + "'");
			}
		}
		JsonArray size = asset.getAsJsonArray("texture");
		if (model.textureWidth != size.get(0).getAsInt() || model.textureHeight != size.get(1).getAsInt()) {
			problems.add("texture resolution " + model.textureWidth + "x" + model.textureHeight + " but contract says "
					+ size.get(0).getAsInt() + "x" + size.get(1).getAsInt());
		}
		int maxCubes = asset.get("maxCubes").getAsInt();
		if (model.cubes.size() > maxCubes) {
			problems.add(model.cubes.size() + " cubes exceed the budget of " + maxCubes);
		}
		Set<String> required = asset.getAsJsonObject("animations").keySet();
		if (!required.isEmpty()) {
			if (!Files.isRegularFile(animationFile)) {
				problems.add("missing " + animationFile.getFileName() + " (export with the GeckoLib plugin)");
			} else {
				JsonObject animations = Json.read(animationFile).getAsJsonObject().getAsJsonObject("animations");
				for (String name : required) {
					if (animations == null || !animations.has(name)) {
						problems.add("missing animation '" + name + "'");
					}
				}
			}
		}
		return problems;
	}

	private static void collectGroups(List<Object> nodes, Set<String> names) {
		for (Object node : nodes) {
			if (node instanceof BbModel.Group group) {
				names.add(group.name());
				collectGroups(group.children(), names);
			}
		}
	}

	private static byte[] texture(Path sources, String id, BbModel model) throws IOException {
		Path png = sources.resolve(id + ".png");
		if (Files.isRegularFile(png)) {
			return Files.readAllBytes(png);
		}
		String source = model.firstTextureSource;
		if (source == null || !source.startsWith("data:image/png;base64,")) {
			throw new IllegalStateException(id + ": no texture (save " + id + ".png next to the model)");
		}
		return java.util.Base64.getDecoder().decode(source.substring(source.indexOf(',') + 1));
	}

	/** Anchor bones ({@code anchor_<name>}) -> block positions relative to the arena origin (Minecraft axes). */
	private static JsonObject anchorsFromModel(BbModel model) {
		Map<String, double[]> origins = new LinkedHashMap<>();
		collectOrigins(model.roots, origins);
		JsonObject anchors = new JsonObject();
		origins.forEach((name, origin) -> {
			if (name.startsWith("anchor_")) {
				// Blockbench +X is Minecraft +X for block models; pixels -> blocks.
				anchors.add(name.substring("anchor_".length()), vec(origin[0] / 16, origin[1] / 16, origin[2] / 16));
			}
		});
		return anchors;
	}

	private static void collectOrigins(List<Object> nodes, Map<String, double[]> origins) {
		for (Object node : nodes) {
			if (node instanceof BbModel.Group group) {
				origins.put(group.name(), group.origin());
				collectOrigins(group.children(), origins);
			}
		}
	}

	// ---- placeholders --------------------------------------------------------------------------------------

	static JsonObject placeholderGeometry(JsonObject asset) {
		String id = asset.get("id").getAsString();
		JsonArray textureSize = asset.getAsJsonArray("texture");
		JsonArray bones = new JsonArray();
		boolean arena = id.equals("duel_arena");
		JsonObject anchors = arena ? ArenaLayouts.defaultAnchors() : new JsonObject();
		for (String name : asset.getAsJsonObject("bones").keySet()) {
			JsonObject bone = new JsonObject();
			bone.addProperty("name", name);
			if (!name.equals("root")) {
				bone.addProperty("parent", "root");
			}
			if (arena && name.startsWith("anchor_")) {
				JsonArray position = anchors.getAsJsonArray(name.substring("anchor_".length()));
				bone.add("pivot", vec(-position.get(0).getAsDouble() * 16, position.get(1).getAsDouble() * 16,
						position.get(2).getAsDouble() * 16));
			} else {
				bone.add("pivot", vec(0, 0, 0));
			}
			JsonArray cubes = new JsonArray();
			if (name.equals("root")) {
				// A visible stand-in: the playing field plate for the arena, a small box otherwise.
				cubes.add(arena ? cube(-72, 0, -104, 144, 1, 208) : cube(-4, 0, -4, 8, 8, 8));
			} else if (!name.startsWith("anchor_") && !name.startsWith("card_slot_") && !name.endsWith("_slot")) {
				cubes.add(cube(-1, 8, -1, 2, 2, 2));
			}
			if (!cubes.isEmpty()) {
				bone.add("cubes", cubes);
			}
			bones.add(bone);
		}
		JsonObject description = new JsonObject();
		description.addProperty("identifier", "geometry." + NAMESPACE + "." + id);
		description.addProperty("texture_width", textureSize.get(0).getAsInt());
		description.addProperty("texture_height", textureSize.get(1).getAsInt());
		JsonObject geometry = new JsonObject();
		geometry.add("description", description);
		geometry.add("bones", bones);
		JsonArray list = new JsonArray();
		list.add(geometry);
		JsonObject root = new JsonObject();
		root.addProperty("format_version", "1.12.0");
		root.add("minecraft:geometry", list);
		return root;
	}

	private static JsonObject cube(double x, double y, double z, double sx, double sy, double sz) {
		JsonObject cube = new JsonObject();
		cube.add("origin", vec(x, y, z));
		cube.add("size", vec(sx, sy, sz));
		cube.add("uv", vec(0, 0));
		return cube;
	}

	static JsonObject placeholderAnimations(JsonObject asset) {
		JsonObject animations = new JsonObject();
		for (var entry : asset.getAsJsonObject("animations").entrySet()) {
			JsonObject animation = new JsonObject();
			animation.addProperty("loop", entry.getValue().getAsString().startsWith("loop"));
			JsonObject bones = new JsonObject();
			JsonObject root = new JsonObject();
			JsonObject rotation = new JsonObject();
			rotation.add("vector", vec(0, 0, 0));
			root.add("rotation", rotation);
			bones.add("root", root);
			animation.add("bones", bones);
			animations.add(entry.getKey(), animation);
		}
		JsonObject root = new JsonObject();
		root.addProperty("format_version", "1.8.0");
		root.add("animations", animations);
		root.addProperty("geckolib_format_version", 2);
		return root;
	}

	/** Labelled checkerboard so placeholders are obvious in game. */
	static byte[] placeholderTexture(JsonObject asset) throws IOException {
		int width = asset.getAsJsonArray("texture").get(0).getAsInt();
		int height = asset.getAsJsonArray("texture").get(1).getAsInt();
		BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
		Graphics2D g = image.createGraphics();
		int cell = Math.max(2, width / 8);
		for (int y = 0; y < height; y += cell) {
			for (int x = 0; x < width; x += cell) {
				g.setColor(((x + y) / cell) % 2 == 0 ? new Color(0xFF00FF) : new Color(0x202020));
				g.fillRect(x, y, cell, cell);
			}
		}
		g.dispose();
		java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
		if (!ImageIO.write(image, "png", out)) {
			throw new UncheckedIOException(new IOException("No PNG writer"));
		}
		return out.toByteArray();
	}

	static JsonArray vec(double... values) {
		return GeoConverterAccess.array(values);
	}

	/** Bridge to the package-private number formatting of the geo converter. */
	private static final class GeoConverterAccess {
		static JsonArray array(double... values) {
			JsonArray array = new JsonArray();
			for (double value : values) {
				double rounded = Math.round(value * 10_000d) / 10_000d;
				if (rounded == Math.rint(rounded)) {
					array.add((long) rounded);
				} else {
					array.add(rounded);
				}
			}
			return array;
		}
	}
}
