modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Zancrow321/MinecraftYGO/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "jadm_logo.png"
displayURL = "https://github.com/Zancrow321/MinecraftYGO"
authors = "${mod_authors}"
credits = "Duel engine: OCG-Core by the Project Ignis team (AGPL-3.0). Monster models: iconmaster (MIT). Duel disk model: burning-icecream (CC BY-NC 4.0)."
description = '''${mod_description}'''
logoBlur = false

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "${geckolib_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "${curios_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "figura"
type = "optional"
versionRange = "[0.1.5,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "kubejs"
type = "optional"
versionRange = "${kubejs_version_range}"
ordering = "NONE"
side = "BOTH"
