package io.github.zancrow321.minecraftygo.engine.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.random.RandomGenerator;

/**
 * The booster sets cards come in: the modeled pool's, generated by {@code tools/carddata/build_collection.py}, or
 * the booster products of a wider pool. Only pool cards are listed, so every pack is playable.
 */
public record BoosterSets(Map<String, BoosterSet> sets) {
    public static final String RESOURCE = "/minecraftygo/sets.json";
    /** Cards in a pack: eight commons and one rare-or-better, as in the original boosters. */
    public static final int PACK_SIZE = 9;

    public enum Rarity {
        COMMON, RARE, SUPER, ULTRA, SECRET;

        public static Rarity parse(String id) {
            return valueOf(id.toUpperCase(java.util.Locale.ROOT));
        }

        public String id() {
            return name().toLowerCase(java.util.Locale.ROOT);
        }

        /** The pack slot a rarity as printed (e.g. {@code Starlight Rare}) falls into. */
        public static Rarity ofPrinted(String printed) {
            String r = printed.toLowerCase(java.util.Locale.ROOT);
            if (r.contains("short print") || r.contains("normal parallel")) {
                return COMMON;
            }
            if (r.contains("secret") || r.contains("starlight") || r.contains("collector") || r.contains("ghost")
                    || r.contains("grand master") || r.contains("quarter century")) {
                return SECRET;
            }
            if (r.contains("ultra") || r.contains("ultimate") || r.contains("gold") || r.contains("platinum")) {
                return ULTRA;
            }
            if (r.contains("super")) {
                return SUPER;
            }
            if (r.contains("rare") || r.contains("starfoil") || r.contains("shatterfoil")) {
                return RARE;
            }
            return COMMON;
        }
    }

    public record Card(int code, Rarity rarity) {
    }

    public record BoosterSet(String id, String code, String name, List<Card> cards) {
        public BoosterSet {
            cards = List.copyOf(cards);
        }

        public List<Card> of(Rarity rarity) {
            return cards.stream().filter(c -> c.rarity() == rarity).toList();
        }

        /**
         * Opens a pack: eight commons and one card that is secret (1 in 24), ultra (1 in 12), super (1 in 6) or
         * rare, falling back to the next lower rarity the set doesn't have.
         */
        public List<Card> open(RandomGenerator random) {
            Map<Rarity, List<Card>> byRarity = new EnumMap<>(Rarity.class);
            for (Rarity r : Rarity.values()) {
                byRarity.put(r, of(r));
            }
            List<Card> pack = new ArrayList<>(PACK_SIZE);
            List<Card> commons = byRarity.get(Rarity.COMMON).isEmpty() ? cards : byRarity.get(Rarity.COMMON);
            for (int i = 0; i < PACK_SIZE - 1; i++) {
                pack.add(commons.get(random.nextInt(commons.size())));
            }
            double roll = random.nextDouble();
            Rarity foil = roll < 1 / 24.0 ? Rarity.SECRET : roll < 1 / 24.0 + 1 / 12.0 ? Rarity.ULTRA
                    : roll < 1 / 24.0 + 1 / 12.0 + 1 / 6.0 ? Rarity.SUPER : Rarity.RARE;
            while (foil.ordinal() > 0 && byRarity.get(foil).isEmpty()) {
                foil = Rarity.values()[foil.ordinal() - 1];
            }
            List<Card> slot = byRarity.get(foil).isEmpty() ? cards : byRarity.get(foil);
            pack.add(slot.get(random.nextInt(slot.size())));
            return pack;
        }
    }

    public BoosterSets {
        sets = java.util.Collections.unmodifiableMap(new LinkedHashMap<>(sets));
    }

    public BoosterSet get(String id) {
        return sets.get(id);
    }

    /** The rarity a card has in a set, or {@code null} when it isn't in it. */
    public Rarity rarity(String setId, int code) {
        BoosterSet set = sets.get(setId);
        if (set == null) {
            return null;
        }
        return set.cards().stream().filter(c -> c.code() == code).map(Card::rarity).findFirst().orElse(null);
    }

    /**
     * The booster products as sets, each with only the cards in the pool. A card printed in several rarities in
     * one product gets the first one listed.
     */
    public static BoosterSets fromProducts(Products products, CardPool pool) {
        Map<String, BoosterSet> sets = new LinkedHashMap<>();
        for (Products.Product product : products.products()) {
            if (product.kind() != Products.Kind.BOOSTER) {
                continue;
            }
            List<Card> cards = product.cards().stream().filter(p -> pool.contains(p.code()))
                    .map(p -> new Card(p.code(), Rarity.ofPrinted(p.rarity()))).toList();
            if (!cards.isEmpty()) {
                sets.put(product.id(), new BoosterSet(product.id(), product.code(), product.name(), cards));
            }
        }
        return new BoosterSets(sets);
    }

    /** The booster sets of the modeled pool. */
    public static BoosterSets loadBundled() {
        try (InputStream in = BoosterSets.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("Missing " + RESOURCE);
            }
            Map<String, BoosterSet> sets = new LinkedHashMap<>();
            for (JsonElement e : JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8))
                    .getAsJsonArray()) {
                JsonObject o = e.getAsJsonObject();
                List<Card> cards = new ArrayList<>();
                for (JsonElement c : o.getAsJsonArray("cards")) {
                    JsonObject card = c.getAsJsonObject();
                    cards.add(new Card(card.get("code").getAsInt(), Rarity.parse(card.get("rarity").getAsString())));
                }
                String id = o.get("id").getAsString();
                sets.put(id, new BoosterSet(id, o.get("code").getAsString(), o.get("name").getAsString(), cards));
            }
            return new BoosterSets(sets);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
