package io.github.zancrow321.minecraftygo.engine.data;

import io.github.zancrow321.minecraftygo.engine.script.DirectoryScriptProvider;
import io.github.zancrow321.minecraftygo.engine.script.ZipScriptProvider;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.function.Function;

/** Loads the data shipped inside the engine/mod jar (generated by {@code :tools:generatePool}). */
public final class BundledData {
	public static final String CARDS = "minecraftygo/data/cards.json";
	public static final String POOL = "minecraftygo/data/pool.json";
	public static final String TEXTS = "minecraftygo/data/texts_en.json";
	public static final String SETS = "minecraftygo/data/sets.json";
	public static final String SCRIPTS = "minecraftygo/scripts.zip";
	/** Folder precedence inside scripts.zip: GOAT variants are separate codes, so the order rarely matters. */
	public static final List<String> SCRIPT_FOLDERS = DirectoryScriptProvider.DEFAULT_ORDER;

	private BundledData() {}

	public static JsonCardDatabase cards() {
		return readText(CARDS, JsonCardDatabase::read);
	}

	public static CardPool pool() {
		return readText(POOL, CardPool::read);
	}

	public static CardTexts texts() {
		return readText(TEXTS, CardTexts::read);
	}

	public static ZipScriptProvider scripts() {
		try (InputStream in = open(SCRIPTS)) {
			return ZipScriptProvider.read(in, SCRIPT_FOLDERS);
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}
	}

	private static <T> T readText(String resource, Function<Reader, T> parser) {
		try (Reader reader = new InputStreamReader(open(resource), StandardCharsets.UTF_8)) {
			return parser.apply(reader);
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}
	}

	private static InputStream open(String resource) {
		InputStream in = BundledData.class.getClassLoader().getResourceAsStream(resource);
		if (in == null) {
			throw new IllegalStateException("Missing bundled resource " + resource);
		}
		return in;
	}
}
