package io.github.zancrow321.minecraftygo.engine.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static io.github.zancrow321.minecraftygo.engine.OcgConstants.*;

/**
 * The cards a server plays with, and the monster model for each modeled card. The modeled pool is generated by
 * {@code tools/models/import_models.py}; {@link #everything} widens it to every bundled card.
 *
 * @param cutoff      the era cutoff date (ISO, e.g. {@code 2000-07-13}) of the modeled pool, empty for the others
 * @param monsters    passcodes of the monsters handed out (packs, NPC decks), without alternate artworks
 * @param spellsTraps passcodes of the spells and traps handed out, without alternate artworks
 * @param models      passcode to model id, e.g. {@code blue_eyes_white_dragon}
 * @param playable    every card a deck may hold: the above, their alternate artworks and the starter deck cards
 */
public record CardPool(String cutoff, List<Integer> monsters, List<Integer> spellsTraps, Map<Integer, Model> models,
                       Set<Integer> playable) {
    public static final String POOL_RESOURCE = "/minecraftygo/pool.json";
    public static final String MODELS_RESOURCE = "/minecraftygo/models.json";
    public static final String BROKEN_RESOURCE = "/minecraftygo/broken.json";
    /** The decks handed to new players; their cards are always playable. */
    public static final List<String> STARTER_DECKS = List.of("starter_yugi", "starter_kaiba");

    /**
     * @param id         the model's resource name under {@code geo/monster/}, {@code animations/monster/} and
     *                   {@code textures/monster/}
     * @param width      the larger horizontal extent of the model, in blocks
     * @param height     the model's height above its origin, in blocks
     * @param animations the animations the model has; there is always an {@code idle} when there are any
     */
    public record Model(int code, String id, double width, double height, List<String> animations) {
    }

    public CardPool {
        monsters = List.copyOf(monsters);
        spellsTraps = List.copyOf(spellsTraps);
        models = Collections.unmodifiableMap(new LinkedHashMap<>(models));
        playable = Set.copyOf(playable);
    }

    /** The pool for a mode, built from the bundled data. */
    public static CardPool of(PoolMode mode, CardDatabase cards) {
        CardPool modeled = loadBundled();
        return mode == PoolMode.ALL ? everything(cards, modeled.models()) : modeled;
    }

    /** The modeled pool: monsters with a model and the spells and traps of their era. */
    public static CardPool loadBundled() {
        JsonObject pool = read(POOL_RESOURCE).getAsJsonObject();
        Map<Integer, Model> models = new LinkedHashMap<>();
        for (JsonElement element : read(MODELS_RESOURCE).getAsJsonArray()) {
            JsonObject o = element.getAsJsonObject();
            List<String> animations = new ArrayList<>();
            for (JsonElement a : o.getAsJsonArray("animations")) {
                animations.add(a.getAsString());
            }
            int code = o.get("code").getAsInt();
            models.put(code, new Model(code, o.get("model").getAsString(), o.get("width").getAsDouble(),
                    o.get("height").getAsDouble(), List.copyOf(animations)));
        }
        List<Integer> monsters = ints(pool.getAsJsonArray("monsters"));
        List<Integer> spellsTraps = ints(pool.getAsJsonArray("spellsTraps"));
        Set<Integer> playable = new HashSet<>(monsters);
        playable.addAll(spellsTraps);
        for (String deck : STARTER_DECKS) {
            Deck starter = Deck.bundled(deck);
            playable.addAll(starter.main());
            playable.addAll(starter.extra());
        }
        return new CardPool(pool.get("cutoff").getAsString(), monsters, spellsTraps, models, playable);
    }

    /**
     * Every bundled card except tokens and the cards listed in {@value #BROKEN_RESOURCE} (scripts that don't load).
     */
    public static CardPool everything(CardDatabase cards, Map<Integer, Model> models) {
        Set<Integer> broken = new HashSet<>(ints(read(BROKEN_RESOURCE).getAsJsonArray()));
        List<Integer> monsters = new ArrayList<>();
        List<Integer> spellsTraps = new ArrayList<>();
        Set<Integer> playable = new HashSet<>();
        for (CardInfo card : cards.all()) {
            int code = card.code();
            int original = alternateArtOf(card);
            if (card.is(TYPE_TOKEN) || broken.contains(code) || broken.contains(original)) {
                continue;
            }
            playable.add(code);
            if (original != code) {
                continue;
            }
            (card.is(TYPE_MONSTER) ? monsters : spellsTraps).add(code);
        }
        Collections.sort(monsters);
        Collections.sort(spellsTraps);
        return new CardPool("", monsters, spellsTraps, models, playable);
    }

    /**
     * @return the original card's passcode if this is an alternate artwork of it (the core treats the two as one
     *         card, see ocgcore's {@code interpreter::register_card}), otherwise the card's own
     */
    public static int alternateArtOf(CardInfo card) {
        int alias = card.data().alias();
        return alias != 0 && Math.abs(alias - card.code()) < 10 ? alias : card.code();
    }

    /** Whether a deck may hold this card on this server. */
    public boolean contains(int code) {
        return playable.contains(code);
    }

    /** @return the model for a card, or {@code null} if it has none */
    public Model model(int code) {
        return models.get(code);
    }

    private static List<Integer> ints(JsonArray array) {
        List<Integer> out = new ArrayList<>(array.size());
        for (JsonElement e : array) {
            out.add(e.getAsInt());
        }
        return out;
    }

    private static JsonElement read(String resource) {
        try (InputStream in = CardPool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Missing " + resource);
            }
            return JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
