package io.github.zancrow321.minecraftygo.engine.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The playable card pool and the monster model for each modeled card, generated by
 * {@code tools/models/import_models.py}.
 *
 * @param cutoff      the era cutoff date (ISO, e.g. {@code 2000-07-13}); spells and traps up to it are in the pool
 * @param monsters    passcodes of the modeled monsters
 * @param spellsTraps passcodes of the spells and traps in the era
 * @param models      passcode to model id, e.g. {@code blue_eyes_white_dragon}
 */
public record CardPool(String cutoff, List<Integer> monsters, List<Integer> spellsTraps, Map<Integer, Model> models) {
    public static final String POOL_RESOURCE = "/minecraftygo/pool.json";
    public static final String MODELS_RESOURCE = "/minecraftygo/models.json";

    /**
     * @param id         the model's resource name under {@code geo/monster/}, {@code animations/monster/} and
     *                   {@code textures/monster/}
     * @param width      the larger horizontal extent of the model, in blocks
     * @param height     the model's height above its origin, in blocks
     * @param animations the animations the model has; there is always an {@code idle} when there are any
     */
    public record Model(int code, String id, double width, double height, List<String> animations) {
    }

    public CardPool {
        monsters = List.copyOf(monsters);
        spellsTraps = List.copyOf(spellsTraps);
        models = Collections.unmodifiableMap(new LinkedHashMap<>(models));
    }

    public static CardPool loadBundled() {
        JsonObject pool = read(POOL_RESOURCE).getAsJsonObject();
        Map<Integer, Model> models = new LinkedHashMap<>();
        for (JsonElement element : read(MODELS_RESOURCE).getAsJsonArray()) {
            JsonObject o = element.getAsJsonObject();
            List<String> animations = new ArrayList<>();
            for (JsonElement a : o.getAsJsonArray("animations")) {
                animations.add(a.getAsString());
            }
            int code = o.get("code").getAsInt();
            models.put(code, new Model(code, o.get("model").getAsString(), o.get("width").getAsDouble(),
                    o.get("height").getAsDouble(), List.copyOf(animations)));
        }
        return new CardPool(pool.get("cutoff").getAsString(), ints(pool.getAsJsonArray("monsters")),
                ints(pool.getAsJsonArray("spellsTraps")), models);
    }

    /** @return the model for a card, or {@code null} if it has none */
    public Model model(int code) {
        return models.get(code);
    }

    private static List<Integer> ints(JsonArray array) {
        List<Integer> out = new ArrayList<>(array.size());
        for (JsonElement e : array) {
            out.add(e.getAsInt());
        }
        return out;
    }

    private static JsonElement read(String resource) {
        try (InputStream in = CardPool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Missing " + resource);
            }
            return JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
