package io.github.zancrow321.minecraftygo.engine.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Every TCG product in release order, generated by {@code tools/carddata/build_collection.py}: the steps a server
 * unlocks one after another, and what each one contains.
 *
 * @param products the products, oldest first
 * @param ocgOnly  cards never printed in the TCG, with their OCG release date
 */
public record Products(List<Product> products, Map<Integer, LocalDate> ocgOnly) {
    public static final String RESOURCE = "/minecraftygo/products.json";

    /** What sort of product it is, roughly; pack formats per kind are still to come. */
    public enum Kind {
        BOOSTER, DECK, TIN, PROMO, SPECIAL
    }

    /** A card in a product, with its rarity as printed, e.g. {@code Ultra Rare} or {@code Starlight Rare}. */
    public record Printing(int code, String rarity) {
    }

    /**
     * @param id       unique id, the slug of the name, e.g. {@code legend_of_blue_eyes_white_dragon}
     * @param code     the set code, e.g. {@code LOB}; not unique (promos share theirs)
     * @param cards    every card in the product
     * @param newCards the cards this is the first TCG product for; empty for a reprint-only product
     */
    public record Product(String id, String code, String name, LocalDate date, Kind kind, List<Printing> cards,
                          List<Integer> newCards) {
        public Product {
            cards = List.copyOf(cards);
            newCards = List.copyOf(newCards);
        }
    }

    public Products {
        products = List.copyOf(products);
        ocgOnly = Collections.unmodifiableMap(new LinkedHashMap<>(ocgOnly));
    }

    /** @return the product with this id, or {@code null} */
    public Product get(String id) {
        return products.stream().filter(p -> p.id().equals(id)).findFirst().orElse(null);
    }

    public static Products loadBundled() {
        try (InputStream in = Products.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("Missing " + RESOURCE);
            }
            JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8))
                    .getAsJsonObject();
            List<Product> products = new ArrayList<>();
            for (JsonElement e : root.getAsJsonArray("products")) {
                JsonObject o = e.getAsJsonObject();
                List<Printing> cards = new ArrayList<>();
                for (JsonElement c : o.getAsJsonArray("cards")) {
                    JsonArray pair = c.getAsJsonArray();
                    cards.add(new Printing(pair.get(0).getAsInt(), pair.get(1).getAsString()));
                }
                List<Integer> newCards = new ArrayList<>();
                for (JsonElement c : o.getAsJsonArray("new")) {
                    newCards.add(c.getAsInt());
                }
                products.add(new Product(o.get("id").getAsString(), o.get("code").getAsString(),
                        o.get("name").getAsString(), LocalDate.parse(o.get("date").getAsString()),
                        Kind.valueOf(o.get("kind").getAsString().toUpperCase(java.util.Locale.ROOT)), cards,
                        newCards));
            }
            Map<Integer, LocalDate> ocgOnly = new LinkedHashMap<>();
            for (JsonElement e : root.getAsJsonArray("ocgOnly")) {
                JsonArray pair = e.getAsJsonArray();
                ocgOnly.put(pair.get(0).getAsInt(), LocalDate.parse(pair.get(1).getAsString()));
            }
            return new Products(products, ocgOnly);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
