package io.github.zancrow321.jadm.engine.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Every TCG Forbidden & Limited List with the date it took effect, oldest first, generated by
 * {@code tools/carddata/build_banlists.py}.
 */
public record Banlists(List<Dated> lists) {
    public static final String RESOURCE = "/jadm/banlists.json";

    public record Dated(LocalDate date, Banlist banlist) {
    }

    public Banlists {
        lists = List.copyOf(lists);
    }

    /** @return the list in force on {@code date}: the newest one not after it, or the oldest one before them all */
    public Banlist at(LocalDate date) {
        Banlist found = lists.get(0).banlist();
        for (Dated d : lists) {
            if (d.date().isAfter(date)) {
                break;
            }
            found = d.banlist();
        }
        return found;
    }

    /** The newest list. */
    public Banlist latest() {
        return lists.get(lists.size() - 1).banlist();
    }

    public static Banlists loadBundled() {
        try (InputStream in = Banlists.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("Missing " + RESOURCE);
            }
            List<Dated> lists = new ArrayList<>();
            for (JsonElement e : JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8))
                    .getAsJsonArray()) {
                JsonObject o = e.getAsJsonObject();
                Map<Integer, Integer> limits = new HashMap<>();
                o.getAsJsonObject("limits").entrySet()
                        .forEach(l -> limits.put(Integer.parseInt(l.getKey()), l.getValue().getAsInt()));
                lists.add(new Dated(LocalDate.parse(o.get("date").getAsString()),
                        new Banlist(o.get("name").getAsString(), limits)));
            }
            return new Banlists(lists);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
