package io.github.zancrow321.jadm.engine.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.zancrow321.jadm.engine.CardData;
import io.github.zancrow321.jadm.engine.CardDataProvider;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The bundled card pool, generated by {@code tools/carddata/build_carddata.py}.
 */
public final class CardDatabase implements CardDataProvider {
    public static final String RESOURCE = "/jadm/cards.json";

    private final Map<Integer, CardInfo> cards;

    private CardDatabase(Map<Integer, CardInfo> cards) {
        this.cards = Collections.unmodifiableMap(cards);
    }

    /** Loads the database bundled with the mod. */
    public static CardDatabase loadBundled() {
        try (InputStream in = CardDatabase.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException("Missing card database " + RESOURCE);
            }
            return load(new InputStreamReader(in, StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    public static CardDatabase load(Reader reader) {
        JsonArray array = JsonParser.parseReader(reader).getAsJsonArray();
        Map<Integer, CardInfo> cards = new HashMap<>();
        for (JsonElement element : array) {
            CardInfo card = parse(element.getAsJsonObject());
            cards.put(card.code(), card);
        }
        return new CardDatabase(cards);
    }

    private static CardInfo parse(JsonObject o) {
        JsonArray setcodeArray = o.getAsJsonArray("setcodes");
        int[] setcodes = new int[setcodeArray.size()];
        for (int i = 0; i < setcodes.length; i++) {
            setcodes[i] = setcodeArray.get(i).getAsInt();
        }
        CardData data = new CardData(o.get("code").getAsInt(), o.get("alias").getAsInt(), setcodes,
                o.get("type").getAsInt(), o.get("level").getAsInt(), o.get("attribute").getAsInt(),
                o.get("race").getAsLong(), o.get("attack").getAsInt(), o.get("defense").getAsInt(),
                o.get("lscale").getAsInt(), o.get("rscale").getAsInt(), o.get("linkMarker").getAsInt());
        List<String> strings = new ArrayList<>();
        for (JsonElement s : o.getAsJsonArray("strings")) {
            strings.add(s.getAsString());
        }
        return new CardInfo(data, o.get("name").getAsString(), o.get("desc").getAsString(), List.copyOf(strings));
    }

    /** @return the card, or {@code null} if it isn't in the pool */
    public CardInfo card(int code) {
        return cards.get(code);
    }

    public Collection<CardInfo> all() {
        return cards.values();
    }

    public String name(int code) {
        CardInfo card = cards.get(code);
        return card == null ? "#" + code : card.name();
    }

    @Override
    public CardData get(int code) {
        CardInfo card = cards.get(code);
        return card == null ? null : card.data();
    }
}
